[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.optimized"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
NODE_ENV = "production" 